server:
  port: 8084

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
        routes:
          - id: authentication
            uri: lb://authentication
            predicates:
              - Path=/authentication/**
            filters:
              - RewritePath=/authentication/(?<path>.*), /$\{path}

