server:
  port: 8084

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
        routes:
          - id: admin
            uri: lb://admin
            predicates:
              - Path=/admin/**
            filters:
              - RewritePath=/admin/(?<path>.*), /$\{path}

