version: '3'
services:

  consul-server:
    image: consul-server
    build:
      context: ./consul-server
      dockerfile: Dockerfile
    tty: true
    ports: 
      - "8500:8500"
    networks:
      static-network:
        ipv4_address: 172.20.0.2

  admin-service:
     image: admin_service
     build:
       context: ./services/adminService
       dockerfile: Dockerfile
     tty: true
     ports:
       - "8086:8086"
     networks:
       - static-network
     depends_on:
       - consul-server
  ad-service:
     image: ad_service
     build:
       context: ./services/adService
       dockerfile: Dockerfile
     tty: true
     ports:
       - "8085:8085"
     networks:
       - static-network
     depends_on:
       - consul-server
  gateway:
    image: gateway
    build:
      context: ./services/gateway
      dockerfile: Dockerfile
    tty: true
    ports: 
      - "8084:8084"
    networks:
      - static-network
    depends_on:
      - consul-server


networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16