version: '3'
services:

  consul-server:
    image: consul-server
    build:
      context: ./consul-server
      dockerfile: Dockerfile
    tty: true
    ports: 
      - "8500:8500"
    networks:
      static-network:
        ipv4_address: 172.20.0.2

  authentication-service:
    image: authenticatione_service
    build:
      context: ./services/authenticationService
      dockerfile: Dockerfile
    tty: true
    ports: 
      - "8087:8087"
    networks:
      - static-network
    depends_on: 
      - consul-server

    
  gateway:
    image: gateway
    build:
      context: ./services/gateway
      dockerfile: Dockerfile
    tty: true
    ports: 
      - "8084:8084"
    networks:
      - static-network
    depends_on:
      - consul-server


networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16